### ISSUE TITLE
Consider support ASGI 3.0

### ISSUE THREAD

**Issue by Skeen** [JohnDoee/txasgiresource#1]
This resource currently only supports the ASGI 2.0 spec, and calls applications with the old two-callable scheme. Consider updating it to the ASGI 3.0 spec. See: https://github.com/django/asgiref/blob/master/specs/asgi.rst#applications

For backwards compatability, you can use [asgiref.compatability's guarantee_single_callable](https://github.com/django/asgiref/blob/master/asgiref/compatibility.py#L39).

As a work-around an ASGI 3.0 app can also be turned into an ASGI 2.0 app, by using a lambda. `lambda scope: partial(app, scope)`.

**Comment by JohnDoee** [comment]
Thanks for brining it up, I've added support for it now.
